title: Hello, world! I'm Stephan Wensel
description: > # this means to ignore newlines until "baseurl:"
  Website of Stephan Wensel. Data Scientist in the making, football enthusiast, curious mind. Shaped in Magdeburg, based in Bielefeld.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https://stephanwensel.github.io" # the base hostname & protocol for your site, e.g. http://stephan-wensel.de
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Stephan Wensel
author-img: stephan-wensel.jpg
about-author: Data Scientist in the making, football enthusiast, curious mind. Shaped in Magdeburg, based in Bielefeld.
twitter: StephanWensel # add your Twitter handle
facebook: stephan.wensel # add your Facebook handle
github: stephanwensel # add your Github handle
linkedin: # add your Linkedin handle
email: St.Wensel@gmx.de # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
